apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: coffee-api
  name: coffee-api
spec:
  ports:
  - port: 8585
    protocol: TCP
    targetPort: 8585
  selector:
    app: coffee-api
status:
  loadBalancer: {}
