apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: coffee-api
  name: coffee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coffee-api
    spec:
      containers:
      - image: coffee-no-java:0.0.1
        name: coffee-api
        ports:
        - containerPort: 8585
        resources: {}
status: {}
