# https://kind.sigs.k8s.io/docs/user/configuration/#extra-port-mappings
# This maps the kind port to the host port, for ease of use in testing.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8585
    hostPort: 8585
  - containerPort: 5432
    hostPort: 5432