apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/coffee-api/
images:
- name: coffee-api
  newName: coffee-no-java
  newTag: 0.0.1
patches:
- path: ./coffee-prod-patch.yml
