apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/coffee-api/
images:
- name: coffee-api
  newName: coffee-api-prod
  newTag: 1.0.0
patches:
- path: ./coffee-prod-patch.yml
